### ISSUE TITLE
Issue with datetime_convert.py

### ISSUE THREAD

**Issue by JaC-T** [uvmcs120s2023/CS-120-Advanced-Programming#14]
Description: Prints 03/17/2022 45:10:30 when should print 03/17/2022 10:45:30

Steps to Reproduce: Run Code??

Expected Behavior: Should print 03/17/2022 10:45:30

Actual Behavior: Prints 03/17/2022 45:10:30.

Additional Information

Operating System: Windows

Possible Solution: Swap hours and mins in relevant line

Priority: Medium

Reproducibility: Always

Impact: High

**Comment by Sebas-Thomas** [comment]
Found and corrected issue
